#!/bin/sh
# Create links to executable files
ln -nfs /usr/share/gedit-2/gmate/gmate.py /usr/bin/gmate
ln -nfs /usr/share/gedit-2/gmate/gmate.py /usr/bin/mate
ln -nfs /usr/share/gedit-2/gmate/gmate.py /usr/bin/e

#DEBHELPER#
