#!/bin/sh
mv /usr/share/gtksourceview-2.0/language-specs/ruby.lang /usr/share/gtksourceview-2.0/language-specs/ruby.lang.gmate
mv /usr/share/gtksourceview-2.0/language-specs/ruby.lang.gmate.bak /usr/share/gtksourceview-2.0/language-specs/ruby.lang
